# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Silvia Bucci
description:      'Welcome to my webpage!'
url:              https://silvia1993.github.io/
baseurl:          https://silvia1993.github.io/

author:
  name:           'Silvia Bucci'
  url:            https://twitter.com/SilviaBucci10

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate]

github:
  repo:           https://github.com/silvia1993/silvia1993.github.io
