# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

image: public/profile_image.png

# Setup
title:            Silvia Bucci
tagline:          'A Jekyll theme'
description:      'Welcome to my webpage!'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate]

github:
  repo:           https://github.com/silvia1993/silvia1993.github.io
